export const INTENTS = Object.freeze({
  GET_GENERAL_ADVICE: 'INTENT_GET_GENERAL_ADVICE' as const,
  ESTIMATE_CALORIES: 'INTENT_ESTIMATE_CALORIES' as const,
  RECORD_WEIGHT: 'INTENT_RECORD_WEIGHT' as const,
  RECORD_MEALS_AND_CALORIES: 'INTENT_RECORD_MEALS_AND_CALORIES' as const,
  RECORD_ACTIVITIES_AND_BURN: 'INTENT_RECORD_ACTIVITIES_AND_BURN' as const,
  SET_TIMEZONE: 'SET_TIMEZONE' as const,
  GET_WEEKLY_SUMMARY: 'INTENT_GET_WEEKLY_SUMMARY' as const,
  GET_DAILY_SUMMARY: 'INTENT_GET_DAILY_SUMMARY' as const,
  EDIT_PREVIOUS_ACTION: 'INTENT_EDIT_PREVIOUS_ACTION' as const,
  SET_USER_GENDER: 'SET_USER_GENDER' as const,
  SET_USER_AGE: 'SET_USER_AGE' as const,
  SET_USER_HEIGHT: 'SET_USER_HEIGHT' as const,
});
