export const INTENTS = {
  GET_GENERAL_ADVICE: 'INTENT_GET_GENERAL_ADVICE',
  ESTIMATE_CALORIES: 'INTENT_ESTIMATE_CALORIES',
  RECORD_WEIGHT: 'INTENT_RECORD_WEIGHT',
  RECORD_MEALS_AND_CALORIES: 'INTENT_RECORD_MEALS_AND_CALORIES',
  RECORD_ACTIVITIES_AND_BURN: 'INTENT_RECORD_ACTIVITIES_AND_BURN',
};
